name: UI Automations Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Execute UI Tests
        env:
          PLAYWRIGHT_JSON_OUTPUT_NAME: main-report.json
        run: npx playwright test --reporter=json
        continue-on-error: true

      - name: Log Results to MongoDB
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node log-to-db.js

      - name: Upload Artifacts (Reports & Screenshots)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: playwright-report/
          retention-days: 14